default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("DB_USER_NAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV["DATABASE_PORT"] || '5432' %>

development:
  <<: *default
  database: bills_manager_development

test:
  <<: *default
  database: bills_manager_test

production:
  <<: *default
  database: bills_manager_production
